default:
  statusbar: false
  browser_spellcheck: true
  convert_urls: false
  width: "100%"
  height: "200"
  menubar: false
  plugins: "autolink paste fullscreen table link anchor lists hr advlist image"
  toolbar_items_size: 'small'
  toolbar1: "cut copy paste searchreplace | undo redo | removeformat | fullscreen"
  toolbar2: "bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist | outdent indent blockquote | link unlink anchor | hr | table | image"
  # paste_auto_cleanup_on_paste: true
  # paste_remove_spans: true
  # paste_strip_class_attributes: 'mso'
  # valid_styles: {'*' : 'color,font-weight,text-decoration'}
  paste_data_images: true
