# encoding: utf-8

# Political Parties **************************************************************************
PoliticalParty.destroy_all

pp = PoliticalParty.create(:id => 1)
pp.political_party_translations.create(:name=>"ერთიანი ეროვნული მოძრაობა", :locale=>"ka")
pp.political_party_translations.create(:name=>"United National Movement", :locale=>"en")
pp = PoliticalParty.create(:id => 2)
pp.political_party_translations.create(:name=>"კოალიცია - ქართული ოცნება", :locale=>"ka")
pp.political_party_translations.create(:name=>"Coalition - Georgian Dream", :locale=>"en")
pp = PoliticalParty.create(:id => 3)
pp.political_party_translations.create(:name=>"ქრისტიან დემოკრატიული მოძრაობა", :locale=>"ka")
pp.political_party_translations.create(:name=>"Christian Democratic Movement", :locale=>"en")
pp = PoliticalParty.create(:id => 4)
pp.political_party_translations.create(:name=>"ეროვნულ დემოკრატიული პარტია", :locale=>"ka")
pp.political_party_translations.create(:name=>"National Democratic Party", :locale=>"en")
pp = PoliticalParty.create(:id => 5)
pp.political_party_translations.create(:name=>"ახალი მემარჯვენეების პარტია", :locale=>"ka")
pp.political_party_translations.create(:name=>"New Rights Party", :locale=>"en")
pp = PoliticalParty.create(:id => 6)
pp.political_party_translations.create(:name=>"ლეიბორისტული პარტია", :locale=>"ka")
pp.political_party_translations.create(:name=>"Labor Party", :locale=>"en")

# Economic Categories **************************************************************************
EconomicCategory.destroy_all

ec = EconomicCategory.create(:id => 1)
ec.economic_category_translations.create(:name=>"სოფლის მეურნეობა", :locale=>"ka")
ec.economic_category_translations.create(:name=>"Agriculture", :locale=>"en")
ec = EconomicCategory.create(:id => 2)
ec.economic_category_translations.create(:name=>"ჯანდაცვა", :locale=>"ka")
ec.economic_category_translations.create(:name=>"Healthcare", :locale=>"en")
ec = EconomicCategory.create(:id => 3)
ec.economic_category_translations.create(:name=>"სოციალური უზრუნელყოფა", :locale=>"ka")
ec.economic_category_translations.create(:name=>"Social care", :locale=>"en")
ec = EconomicCategory.create(:id => 4)
ec.economic_category_translations.create(:name=>"განათლება", :locale=>"ka")
ec.economic_category_translations.create(:name=>"Education", :locale=>"en")
ec = EconomicCategory.create(:id => 5)
ec.economic_category_translations.create(:name=>"დასაქმება", :locale=>"ka")
ec.economic_category_translations.create(:name=>"Employment", :locale=>"en")
ec = EconomicCategory.create(:id => 6)
ec.economic_category_translations.create(:name=>"მაკროეკონომიკური საკითხები", :locale=>"ka")
ec.economic_category_translations.create(:name=>"Macroeconomic Issues", :locale=>"en")

# Indicator Categories **************************************************************************
IndicatorCategory.destroy_all

ic = IndicatorCategory.create(:id => 1)
ic.indicator_category_translations.create(:name=>"ფაქტობრივი სიზუსტე", :locale=>"ka")
ic.indicator_category_translations.create(:name=>"Factual Correctness", :locale=>"en")
ic = IndicatorCategory.create(:id => 2)
ic.indicator_category_translations.create(:name=>"შინაგანი თანმიმდევრულობა", :locale=>"ka")
ic.indicator_category_translations.create(:name=>"Internal Consistency", :locale=>"en")
ic = IndicatorCategory.create(:id => 3)
ic.indicator_category_translations.create(:name=>"ეკონომიკური დასაბუთება", :locale=>"ka")
ic.indicator_category_translations.create(:name=>"Economic Reasoning", :locale=>"en")
ic = IndicatorCategory.create(:id => 4)
ic.indicator_category_translations.create(:name=>"განხორციელებადობა", :locale=>"ka")
ic.indicator_category_translations.create(:name=>"Feasibility", :locale=>"en")
ic = IndicatorCategory.create(:id => 5)
ic.indicator_category_translations.create(:name=>"ადგილი იდეოლოგიურ/პოლიტიკურ რუკაზე", :locale=>"ka")
ic.indicator_category_translations.create(:name=>"Placement on Ideological/Policy Map", :locale=>"en")
ic.indicator_category_translations.create(:name=>"იდეოლოგიური ფოკუსი", :locale=>"ka")
ic = IndicatorCategory.create(:id => 6)
ic.indicator_category_translations.create(:name=>"Ideological Focus/Flip-Flops", :locale=>"en")

# Indicators **************************************************************************
Indicator.destroy_all

ind = Indicator.create(:id => 1, :indicator_category_id => 1, :value => 0)
ind.indicator_translations.create(:name=>"ფაქტები არ არის მოყვანილი", :locale=>"ka")
ind.indicator_translations.create(:name=>"no facts are stated", :locale=>"en")
ind = Indicator.create(:id => 2, :indicator_category_id => 1, :value => 1)
ind.indicator_translations.create(:name=>"ტექსტში/განცხადებაში მოყვანილი ყველა ფაქტი არასწორია", :locale=>"ka")
ind.indicator_translations.create(:name=>"all factual statements contained in the text/statement are wrong", :locale=>"en")
ind = Indicator.create(:id => 3, :indicator_category_id => 1, :value => 2)
ind.indicator_translations.create(:name=>"თითქმის ყველა არასწორია", :locale=>"ka")
ind.indicator_translations.create(:name=>"almost all are wrong", :locale=>"en")
ind = Indicator.create(:id => 4, :indicator_category_id => 1, :value => 3)
ind.indicator_translations.create(:name=>"თითქმის მთლიანად არასწორია", :locale=>"ka")
ind.indicator_translations.create(:name=>"mostly wrong", :locale=>"en")
ind = Indicator.create(:id => 5, :indicator_category_id => 1, :value => 4)
ind.indicator_translations.create(:name=>"მხოლოდ რამდენიმე განცხადებაა არასწორი", :locale=>"ka")
ind.indicator_translations.create(:name=>"only a few statements are wrong", :locale=>"en")
ind = Indicator.create(:id => 6, :indicator_category_id => 1, :value => 5)
ind.indicator_translations.create(:name=>"ძირითადად სწორია", :locale=>"ka")
ind.indicator_translations.create(:name=>"mostly correct", :locale=>"en")
ind = Indicator.create(:id => 7, :indicator_category_id => 1, :value => 6)
ind.indicator_translations.create(:name=>"თითქმის ყველა სწორია", :locale=>"ka")
ind.indicator_translations.create(:name=>"almost all are correct", :locale=>"en")
ind = Indicator.create(:id => 8, :indicator_category_id => 1, :value => 7)
ind.indicator_translations.create(:name=>"ყველა განცხადება სწორია (მონაცემებზე ან ობიექტურ შეფასებაზე/მონაცემთა  ანალიზზე დაყრდნობით", :locale=>"ka")
ind.indicator_translations.create(:name=>"all statements are correct (supported by data or rely on an objective assessment/interpretation of the data)", :locale=>"en")

ind = Indicator.create(:id => 9, :indicator_category_id => 2, :value => 1)
ind.indicator_translations.create(:name=>"პოლიტიკური განცხადება თავის თავს ეწინააღდეგება (მაგ. (ა) მუშაობის უფლება თითოეული ადამიანის ფუნდამენტური უფლებაა და სახელმწიფომ უნდა უზრუნველყოს ეს უფლება; (ბ) სახელმწიფო არ უნდა ერეოდეს შრომის ბაზარში", :locale=>"ka")
ind.indicator_translations.create(:name=>"the policy statement is self-contradictory (example: (a) the right to work is a fundamental right of every individual and the state should guarantee this right; (b) the state should not interfere in the labor market)", :locale=>"en")
ind = Indicator.create(:id => 10, :indicator_category_id => 2, :value => 2)
ind.indicator_translations.create(:name=>"თითქმის მთლიანად ურთიერთგამომრიცხავია", :locale=>"ka")
ind.indicator_translations.create(:name=>"almost entirely contradictory", :locale=>"en")
ind = Indicator.create(:id => 11, :indicator_category_id => 2, :value => 3)
ind.indicator_translations.create(:name=>"ძირითადად ურთიერთგამომრიცხავი", :locale=>"ka")
ind.indicator_translations.create(:name=>"mostly contradictory", :locale=>"en")
ind = Indicator.create(:id => 12, :indicator_category_id => 2, :value => 4)
ind.indicator_translations.create(:name=>"მხოლოდ რაღაც დონეზე ურთიერთგამომრიცხავია", :locale=>"ka")
ind.indicator_translations.create(:name=>"only somewhat contradictory", :locale=>"en")
ind = Indicator.create(:id => 13, :indicator_category_id => 2, :value => 5)
ind.indicator_translations.create(:name=>"არ მოიცავს არც ერთ სერიოზულ ურთიერთგამომრიცხავ განცხადებას", :locale=>"ka")
ind.indicator_translations.create(:name=>"does not contain any major contradictions", :locale=>"en")
ind = Indicator.create(:id => 14, :indicator_category_id => 2, :value => 6)
ind.indicator_translations.create(:name=>"თითქმის მთლიანად თანმიმდევრულია", :locale=>"ka")
ind.indicator_translations.create(:name=>"almost entirely consistent", :locale=>"en")
ind = Indicator.create(:id => 15, :indicator_category_id => 2, :value => 7)
ind.indicator_translations.create(:name=>"მთლიანად თანმიმდერვრულია (მაგ. (ა) მუშაობის უფლება ადამინის ფუნდამენტალური უფლებაა და სახელმწიფომ იგი უნდა უზრუნველყოს; (ბ) სახელმწიფომ უნდა შექმნას სამუშაო ადგილები მიუხედავად იმისა ექნებათ თუ არა მათ ღირებულება და მიუხედავად იმისა სჭირდება თუ არა ისინი ეკონომიკას. ", :locale=>"ka")
ind.indicator_translations.create(:name=>"fully consistent (example:  (a) the right to work is a fundamental right of every individual and the state should guarantee this right; (b) the state should create jobs, even if these do not produce any value added and are not needed for the economy, in order to maintain full employment)", :locale=>"en")

ind = Indicator.create(:id => 16, :indicator_category_id => 3, :value => 1)
ind.indicator_translations.create(:name=>"the policy statement makes absolutely no economic sense and if implemented would lead to strongly negative outcomes (“doubling unemployment benefits will increase employment”)", :locale=>"ka")
ind.indicator_translations.create(:name=>"the policy statement makes absolutely no economic sense and if implemented would lead to strongly negative outcomes (“doubling unemployment benefits will increase employment”)", :locale=>"en")
ind = Indicator.create(:id => 17, :indicator_category_id => 3, :value => 2)
ind.indicator_translations.create(:name=>"the policy statement makes almost no economic sense", :locale=>"ka")
ind.indicator_translations.create(:name=>"the policy statement makes almost no economic sense", :locale=>"en")
ind = Indicator.create(:id => 18, :indicator_category_id => 3, :value => 3)
ind.indicator_translations.create(:name=>"the policy statement makes little economic sense", :locale=>"ka")
ind.indicator_translations.create(:name=>"the policy statement makes little economic sense", :locale=>"en")
ind = Indicator.create(:id => 19, :indicator_category_id => 3, :value => 4)
ind.indicator_translations.create(:name=>"the policy would bring about ambiguous results (some positive, some negative, or difficult to know)", :locale=>"ka")
ind.indicator_translations.create(:name=>"the policy would bring about ambiguous results (some positive, some negative, or difficult to know)", :locale=>"en")
ind = Indicator.create(:id => 20, :indicator_category_id => 3, :value => 5)
ind.indicator_translations.create(:name=>"the policy may bring about some positive results", :locale=>"ka")
ind.indicator_translations.create(:name=>"the policy may bring about some positive results", :locale=>"en")
ind = Indicator.create(:id => 21, :indicator_category_id => 3, :value => 6)
ind.indicator_translations.create(:name=>"the policy may bring about mostly positive results", :locale=>"ka")
ind.indicator_translations.create(:name=>"the policy may bring about mostly positive results", :locale=>"en")
ind = Indicator.create(:id => 22, :indicator_category_id => 3, :value => 7)
ind.indicator_translations.create(:name=>"the policy is fully justified economically", :locale=>"ka")
ind.indicator_translations.create(:name=>"the policy is fully justified economically", :locale=>"en")

ind = Indicator.create(:id => 23, :indicator_category_id => 4, :value => 1)
ind.indicator_translations.create(:name=>"the proposed policy cannot be implemented in either the short or medium term – “we will make Georgia the Silicon Valley of the Caucasus”", :locale=>"ka")
ind.indicator_translations.create(:name=>"the proposed policy cannot be implemented in either the short or medium term – “we will make Georgia the Silicon Valley of the Caucasus”", :locale=>"en")
ind = Indicator.create(:id => 24, :indicator_category_id => 4, :value => 2)
ind.indicator_translations.create(:name=>"the proposed policy is very unlikely to be feasible in either the short or medium term", :locale=>"ka")
ind.indicator_translations.create(:name=>"the proposed policy is very unlikely to be feasible in either the short or medium term", :locale=>"en")
ind = Indicator.create(:id => 25, :indicator_category_id => 4, :value => 3)
ind.indicator_translations.create(:name=>"the proposed policy is unlikely to be feasible in either the short or medium term", :locale=>"ka")
ind.indicator_translations.create(:name=>"the proposed policy is unlikely to be feasible in either the short or medium term", :locale=>"en")
ind = Indicator.create(:id => 26, :indicator_category_id => 4, :value => 4)
ind.indicator_translations.create(:name=>"there is a 50% chance for the proposed policy to be feasible in either the short or medium term", :locale=>"ka")
ind.indicator_translations.create(:name=>"there is a 50% chance for the proposed policy to be feasible in either the short or medium term", :locale=>"en")
ind = Indicator.create(:id => 27, :indicator_category_id => 4, :value => 5)
ind.indicator_translations.create(:name=>"the proposed policy is somewhat likely to be feasible in either the short or medium term", :locale=>"ka")
ind.indicator_translations.create(:name=>"the proposed policy is somewhat likely to be feasible in either the short or medium term", :locale=>"en")
ind = Indicator.create(:id => 28, :indicator_category_id => 4, :value => 6)
ind.indicator_translations.create(:name=>"the proposed policy is quite likely to be feasible in either the short or medium term", :locale=>"ka")
ind.indicator_translations.create(:name=>"the proposed policy is quite likely to be feasible in either the short or medium term", :locale=>"en")
ind = Indicator.create(:id => 29, :indicator_category_id => 4, :value => 7)
ind.indicator_translations.create(:name=>"the proposed policy is feasible", :locale=>"ka")
ind.indicator_translations.create(:name=>"the proposed policy is feasible", :locale=>"en")

ind = Indicator.create(:id => 30, :indicator_category_id => 5, :value => 1)
ind.indicator_translations.create(:name=>"the party’s position on the issue is best described as extreme libertarian (the state should guarantee property rights, law and order but should not in any way engage in economic regulation or income redistribution such as support of the poor, unemployed or disabled. These should be taken care of by their families or left to die)", :locale=>"ka")
ind.indicator_translations.create(:name=>"the party’s position on the issue is best described as extreme libertarian (the state should guarantee property rights, law and order but should not in any way engage in economic regulation or income redistribution such as support of the poor, unemployed or disabled. These should be taken care of by their families or left to die)", :locale=>"en")
ind = Indicator.create(:id => 31, :indicator_category_id => 5, :value => 2)
ind.indicator_translations.create(:name=>"the party’s position on the issue is best described as libertarian", :locale=>"ka")
ind.indicator_translations.create(:name=>"the party’s position on the issue is best described as libertarian", :locale=>"en")
ind = Indicator.create(:id => 32, :indicator_category_id => 5, :value => 3)
ind.indicator_translations.create(:name=>"the party’s position on the issue is best described as somewhat libertarian", :locale=>"ka")
ind.indicator_translations.create(:name=>"the party’s position on the issue is best described as somewhat libertarian", :locale=>"en")
ind = Indicator.create(:id => 33, :indicator_category_id => 5, :value => 4)
ind.indicator_translations.create(:name=>"the party’s position on the issue is best described as Western European “social democracy”", :locale=>"ka")
ind.indicator_translations.create(:name=>"the party’s position on the issue is best described as Western European “social democracy”", :locale=>"en")
ind = Indicator.create(:id => 34, :indicator_category_id => 5, :value => 5)
ind.indicator_translations.create(:name=>"the party’s position on the issue is best described as somewhat socialist", :locale=>"ka")
ind.indicator_translations.create(:name=>"the party’s position on the issue is best described as somewhat socialist", :locale=>"en")
ind = Indicator.create(:id => 35, :indicator_category_id => 5, :value => 6)
ind.indicator_translations.create(:name=>"the party’s position on the issue is best described as socialist", :locale=>"ka")
ind.indicator_translations.create(:name=>"the party’s position on the issue is best described as socialist", :locale=>"en")
ind = Indicator.create(:id => 36, :indicator_category_id => 5, :value => 7)
ind.indicator_translations.create(:name=>"the party’s position on the issue is best described as communist (all means of production should be nationalized, businessmen should be prosecuted as “speculators”, the government should run the economy, provide free education, health and social benefits)", :locale=>"ka")
ind.indicator_translations.create(:name=>"the party’s position on the issue is best described as communist (all means of production should be nationalized, businessmen should be prosecuted as “speculators”, the government should run the economy, provide free education, health and social benefits)", :locale=>"en")


puts "###########################################################################"
puts "IMPORTANT: please run 'rake has_permalink:generate_permalinks[Model]' to update the permalinks for Political Parties and Economic Categories"
puts "###########################################################################"
